
export const endPoints = {
  transactionHourData: '/dailyStatsView/lineChart',
  vendorDailyReports: '/dailyStatsView/piechart',
  getUser: '/user/search',
  addUser: '/addUser',
  deleteUser: '/deleteUser/',
  updateUser: '/updateUser/',
  getUsers: '/getUser/',
  trackingCustomet: '/lookup/customers',
  trackingSearch: '/tracking-details',
  customerPiechartReports: '/reports/customersPiechart',
  customerGenerateExcelReports: '/reports/customersTableDataExcel',
  vendorGenerateExcelReports: '/reports/vendorsTableDataExcel',
  vendorPiechartReports: '/reports/vendorsPiechart',
  customerReportsTable: "/reports/customersTableData",
  vendorReportsTable: "/reports/vendorsTableData",
  trackingReportsgeneration: "/tracking-details/download",
  getCustomers: '/customers',
  customerReportsgeneration: "/customers/download",
  addCustomers: '/addCustomer',
  addSubscriptionDetails: '/addSubscriptionDetails',
  getSubscriptionDetails: '/subscriptionDetails',
  updateSubscriptionDetails: '/updateSubscriptionDetails',
  updateCustomer: '/updateCustomer',
  customerCodeExists: '/customerExists',
  getTrackingExcel: '',
  getVendorsList:"/fetchVendorDetails",
  getVendorDetails:"/fetchSendToDetailsbyVendorId",
  updateVendorDetails:"/updateVendorsSendToDetails",
  login:"/login",
  resetPassword:"/resetPassword",
  relogin:"/user/relogin",
  Addqueue:"/activemq-details",
  checkConnection:"/connection-check",
  queueTableData:"/activemqueues",
  queueupdate:"/updateQueue",
  deletedqueue:"/queues",
  checkEmailIdExists:"/checkEmailExists",
  forgotpassword:"/forgotPassword"
  };
  